### ISSUE TITLE
[QUESTION] Radamsa to C

### ISSUE THREAD

**Issue by illera88** [trailofbits/grr#3]
What did you use to migrate Radamsa to C?
The code looks like you used something automatic. Is that correct? 

Nice work!

**Comment by pgoodman** [comment]
Yup! If you download Radamsa then its Makefile includes compilation to C using the OWL Scheme compiler. In GRR, I took that file, then did some evil tricks with macros to stub out stuff, and turn `main` into a function that can be called by GRR itself. I also had to stub out `malloc` and stuff in Radamsa so that I could make sure that repeated calls into Radamsa don't leak memory (real Radamsa just exits when it's done, so it doesn't care about freeing memory :-P )

Does this answer your question?
